config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :podcast_notes
  resources :posts
  get 'posts/archive/:year', to: 'posts#archive', as: 'archive'
  get :search, controller: :search

  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/podcast_note.rb
class PodcastNote < ApplicationRecord
  has_rich_text :note_body
  has_one :action_text_rich_text, class_name: 'ActionText::RichText', as: :record
  
  paginates_per 25
end

app/models/post.rb
class Post < ApplicationRecord
    has_rich_text :body
    has_one :action_text_rich_text, class_name: 'ActionText::RichText', as: :record

    has_one_attached :hero_image

    paginates_per 25

    scope :all_except_last, -> { where.not(id: Post.last.id) }
    # scope :all_by_year, -> { group_by_year(:created_at) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :registerable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/podcast_notes_controller.rb
class PodcastNotesController < ApplicationController
  before_action :set_podcast_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /podcast_notes
  # GET /podcast_notes.json
  def index
    @podcast_notes = PodcastNote.all.order('created_at DESC').page(params[:page])
  end

  # GET /podcast_notes/1
  # GET /podcast_notes/1.json
  def show
  end

  # GET /podcast_notes/new
  def new
    @podcast_note = PodcastNote.new
  end

  # GET /podcast_notes/1/edit
  def edit
  end

  # POST /podcast_notes
  # POST /podcast_notes.json
  def create
    @podcast_note = PodcastNote.new(podcast_note_params)

    respond_to do |format|
      if @podcast_note.save
        format.html { redirect_to @podcast_note, notice: 'Podcast note was successfully created.' }
        format.json { render :show, status: :created, location: @podcast_note }
      else
        format.html { render :new }
        format.json { render json: @podcast_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcast_notes/1
  # PATCH/PUT /podcast_notes/1.json
  def update
    respond_to do |format|
      if @podcast_note.update(podcast_note_params)
        format.html { redirect_to @podcast_note, notice: 'Podcast note was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast_note }
      else
        format.html { render :edit }
        format.json { render json: @podcast_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcast_notes/1
  # DELETE /podcast_notes/1.json
  def destroy
    @podcast_note.destroy
    respond_to do |format|
      format.html { redirect_to podcast_notes_url, notice: 'Podcast note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast_note
      @podcast_note = PodcastNote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def podcast_note_params
      params.require(:podcast_note).permit(:title, :note_body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if Post.last
      @last_post = Post.last
      @posts = Post.all_except_last.order('created_at DESC').page(params[:page])
      @posts_archive = Post.group_by_year(:created_at).count
    else
      redirect_to new_post_path
    end
  end

  def archive
    @start_of_year = Date.new(params[:year].to_i)
    end_of_year = @start_of_year + 1.year

    @posts = Post.where(created_at: @start_of_year..end_of_year).order('created_at DESC').page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :hero_image, :caption)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @posts = Post.ransack(title_or_action_text_rich_text_body_cont: params[:q]).result(distinct: true)
    @podcast_notes = PodcastNote.ransack(title_cont: params[:q]).result(distinct: true)

    respond_to do |format|
      format.html {
        @posts = @posts.page(params[:page])
        @podcast_notes = @podcast_notes.page(params[:page])
      }

      format.json {
        @posts = @posts.limit(5)
        @podcast_notes = @podcast_notes.limit(5)
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def alerts(type)
		if type == notice
			div_class = "alert alert-success alert-dismissible fade show"
		elsif type == alert
			div_class = "alert alert-danger alert-dismissible fade show"
		end

		if type
			content_tag(:div, class: div_class, role: "alert") do
				
				content_tag(:div, type.to_s) + # The plus is used to have multiple items within the content_tag

				content_tag(:button, type: "button", class: "close", data: { dismiss: "alert" }, "aria-label": "Close") do
					content_tag(:span, "&times;".html_safe, "aria-hidden": true)
				end
			end
		end
	end

	def login_helper style = ""
		if current_user 
			link_to 'Logout', destroy_user_session_path, method: :delete, class: style
		else
			(link_to 'Login', new_user_session_path, class: style)
		end
	end
end

app/helpers/podcast_notes_helper.rb
module PodcastNotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500;600;700&family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Font awesome -->
  <script src="https://kit.fontawesome.com/911a8d45ea.js" crossorigin="anonymous"></script>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-169275823-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-169275823-1');
  </script>

</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
    <%= link_to 'Umar Ghouse', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Podcast Notes', podcast_notes_path, class: 'nav-link' %>
        </li>
        <% if current_user %>
        <li class="nav-item">
          <%= link_to new_post_path, class: 'nav-link', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Add New Post' do %>
          <i class="fas fa-plus-circle"></i>
          <% end %>
        </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= login_helper 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>

  <main role="main">
    <div class="container my-3">
      <div id="flash">
        <%= alerts(notice) %>
        <%= alerts(alert) %>
      </div>

      <%= form_with url: search_path, local: true, method: :get, html: { class: "my-2 my-lg-0 mx-auto" } do |form| %>
      <%= form.text_field :q, placeholder: "Search", data: { behavior: "autocomplete" }, class: "search form-control my-3 rounded-pill" %>
      <% end %>

      <%= yield %>
    </div>
  </main>

  <footer class="container">
    <hr>

    <p>&copy; Umar Ghouse <%= Date.today.year %></p>
  </footer>
</body>

</html>

app/views/podcast_notes/_form.html.erb
<%= form_with(model: podcast_note, local: true) do |form| %>
  <% if podcast_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(podcast_note.errors.count, "error") %> prohibited this podcast_note from being saved:</h2>

      <ul>
        <% podcast_note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :note_body %>
    <%= form.rich_text_area :note_body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/podcast_notes/edit.html.erb
<h1>Editing Podcast Note</h1>

<%= render 'form', podcast_note: @podcast_note %>

<%= link_to 'Back', podcast_notes_path, class: 'btn btn-outline-secondary' %>

app/views/podcast_notes/index.html.erb
<h1>Podcast Notes</h1>

<% if current_user %>
  <%= link_to '<i class="fas fa-plus-circle"></i>'.html_safe, new_podcast_note_path, class: 'admin-controls', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Add New Podcast Note' %>
<% end %>

<div class="row">
  <div class="col-md-12">
    <% @podcast_notes.each do |podcast_note| %>
      <div class="row my-5">
        <div class="col-sm-6">
          <h2><%= link_to podcast_note.title, podcast_note %></h2>
        </div>

        <div class="col-sm-6  my-auto">
          <p><%= truncate(strip_tags(podcast_note.note_body.to_s), length: 200) %></p>
          <% if current_user %>
            <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_podcast_note_path(podcast_note), class: 'admin-controls', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Edit' %> | 
            <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, podcast_note, method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, class: 'admin-controls', title: 'Delete' %>
          <% end %>
        </div>
      </div>
    <% end %>

    <%= paginate @podcast_notes %>
  </div>
</div>

app/views/podcast_notes/new.html.erb
<h1>New Podcast Note</h1>

<%= render 'form', podcast_note: @podcast_note %>

<%= link_to 'Back', podcast_notes_path, class: 'btn btn-outline-secondary' %>

app/views/podcast_notes/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to '<i class="fas fa-home"></i>'.html_safe, podcast_notes_path, class: 'breadcrumb-link' %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @podcast_note.title %></li>
  </ol>
</nav>

<h1><%= @podcast_note.title %></h1>
<small class="text-muted"><i class="far fa-clock"></i> <%= local_time(@podcast_note.created_at, :short) %></small>

<% if current_user %>
  <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_podcast_note_path(@podcast_note), class: 'admin-controls', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Edit' %> | 
  <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, @podcast_note, method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, class: 'admin-controls', title: 'Delete' %>
<% end %>

<br>
<br>

<div class="d-flex justify-content-center w-75 mx-auto">
  <%= @podcast_note.note_body %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="custom-file mb-5">
    <%= form.file_field :hero_image, direct_upload: true %>
    <%= form.label :hero_image, class: 'custom-file-label' %>
  </div>

  <div class="form-group mb-5">
    <%= form.text_field :caption, class: 'form-control', placeholder: :caption %>
  </div>

  <div class="form-group mb-5">
    <%= form.text_field :title, class: 'form-control', placeholder: :title %>
  </div>

  <div class="form-group">
    <%= form.rich_text_area :body, class: 'form-control', placeholder: :body %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/archive.html.erb
<h1>All posts from <%= @start_of_year.year %></h1>

<div class="row">
  <div class="col-md-12">
    <% @posts.each do |post| %>
      <div class="row my-5">
        <div class="col-sm-4">
          <% if post.hero_image.attached? %>
            <div class="text-center">
              <image src="<%= url_for(post.hero_image) %>" class="img-fluid">
            </div>
          <% end %>
        </div>

        <div class="col-sm-8">
          <h2><%= link_to post.title, post %></h2>
          <p><%= truncate(strip_tags(post.body.to_s), length: 100) %></p>
          <% if current_user %>
            <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_post_path(post), class: 'admin-controls', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Edit' %> | 
            <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, post, method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, class: 'admin-controls', title: 'Delete' %>
          <% end %>
        </div>
      </div>
    <% end %>

    <%= paginate @posts %>
  </div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: 'btn btn-outline-secondary' %>

app/views/posts/index.html.erb
<div class="row mb-5">
    <div class="col-md-8 my-auto">
      <% if @last_post.hero_image.attached? %>
        <div class="text-center">
          <%= link_to @last_post, class: 'hero-image' do %>
            <image src="<%= url_for(@last_post.hero_image) %>" class="img-fluid">
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="col-md-4 my-auto">
      <h1><%= link_to @last_post.title, @last_post %> <span class="badge badge-pill badge-primary">New</span></h1>
      <p><%= truncate(strip_tags(@last_post.body.to_s), length: 200) %></p>
      <% if current_user %>
        <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_post_path(@last_post), class: 'admin-controls', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Edit' %> | 
        <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, @last_post, method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, class: 'admin-controls', title: 'Delete' %>
      <% end %>
    </div>
</div>

<div class="row">
  <div class="col-md-8">
    <% @posts.each do |post| %>
      <div class="row my-5">
        <div class="col-sm-4">
          <% if post.hero_image.attached? %>
            <div class="text-center">
              <image src="<%= url_for(post.hero_image) %>" class="img-fluid">
            </div>
          <% end %>
        </div>

        <div class="col-sm-8">
          <h2><%= link_to post.title, post %></h2>
          <p><%= truncate(strip_tags(post.body.to_s), length: 100) %></p>
          <% if current_user %>
            <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_post_path(post), class: 'admin-controls', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Edit' %> | 
            <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, post, method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, class: 'admin-controls', title: 'Delete' %>
          <% end %>
        </div>
      </div>
    <% end %>

    <%= paginate @posts %>
  </div>

  <div class="col-md-4">
    <h1>Archive</h1>
    <% @posts_archive.each do |year, number| %>
      <%= link_to year.year, archive_path(2020) %> <span class="badge badge-info"><%= number %></span>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: "btn btn-outline-secondary" %>

app/views/posts/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to '<i class="fas fa-home"></i>'.html_safe, root_path, class: 'breadcrumb-link' %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @post.title %></li>
  </ol>
</nav>

<h1><%= @post.title %></h1>
<small class="text-muted"><i class="far fa-clock"></i> <%= local_time(@post.created_at, :short) %></small>

<% if current_user %>
<%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_post_path(@post), class: 'admin-controls', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Edit' %> |
<%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, @post, method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, class: 'admin-controls', title: 'Delete' %>
<% end %>

<br>

<% if @post.hero_image.attached? %>
<div class="text-center">
  <figure>
    <img src="<%= url_for(@post.hero_image) %>" class="img-fluid" />
    <figcaption class="text-muted"><small><%= @post.caption %></small></figcaption>
  </figure>
</div>
<% end %>

<br>

<div class="d-flex justify-content-center w-75 mx-auto">
  <%= @post.body %>
</div>

app/views/search/search.html.erb
<h1 class="text-center">Here's what we found:</h1>
<hr>
<div class="row">
  <div class="col-md-6">
    <h2 class="text-center">Posts</h2>

    <% @posts.each do |post| %>
    <div class="row my-5">
      <div class="col-sm-4 my-auto">
        <% if post.hero_image.attached? %>
        <div class="text-center">
          <image src="<%= url_for(post.hero_image) %>" class="img-fluid">
        </div>
        <% end %>
      </div>

      <div class="col-sm-8 my-auto">
        <h2><%= link_to post.title, post %></h2>
        <p><%= truncate(strip_tags(post.body.to_s), length: 100) %></p>
        <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_post_path(post), class: 'admin-controls', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Edit' %>
        |
        <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, post, method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, class: 'admin-controls', title: 'Delete' %>
      </div>
    </div>
    <% end %>

    <%= paginate @posts %>
  </div>

  <div class="col-md-6">
    <h2 class="text-center">Podcast Notes</h2>

    <% @podcast_notes.each do |podcast_note| %>
    <div class="row my-5">
      <div class="col-sm-6 my-auto">
        <h2><%= link_to podcast_note.title, podcast_note %></h2>
      </div>

      <div class="col-sm-6 my-auto">
        <p><%= truncate(strip_tags(podcast_note.note_body.to_s), length: 200) %></p>
        <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_podcast_note_path(podcast_note), class: 'admin-controls', data: { toggle: 'tooltip', placement: 'bottom' }, title: 'Edit' %>
        |
        <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, podcast_note, method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, class: 'admin-controls', title: 'Delete' %>
      </div>
    </div>
    <% end %>

    <%= paginate @podcast_notes %>
  </div>
</div>